# .sops.yaml

keys:
  - &mba_minhtung0404 age13dtrv5nadfqvp43e97hh0d23vyzd3qgkqpzn7f0mtm4j5shkkg4swa85sh
  - &mba age1xq7sqcawstlz7ygmsheap6nv0efransz27l94sqwdrjntvnvrp5sef5t9j
  - &mtn_home age17ckhlhhqdxegvpwlghztrcghn26ty4kl5wdruzk8r88e8392kqsqq20dma
  - &mtn_work age1jp2y2wnjwvsn3452qw20ds05f0mhdq0s3tkdk4j6u3srq825nazqxykz04
creation_rules:
  - path_regex: .*\.yaml$
    key_groups:
    - age:
      - *mtn_home
      - *mtn_work
      - *mba_minhtung0404
      - *mba
