# ## Set some color overrides
evaluate-commands %sh{
  autoload_directory() {
      find -L "$1" -type f -name '*\.kak' \
          | sed 's/.*/try %{ source "&" } catch %{ echo -debug Autoload: could not load "&" }/'
  }

  if [ -d "${kak_runtime}/on-load" ]; then
      autoload_directory ${kak_runtime}/on-load
  fi
}

# Color scheme
colorscheme everforest-light-soft

# Set indentation guides
add-highlighter global/indent-guides show-whitespaces -tab " " -spc " " -lf " " -nbsp " "
set-face global Whitespace default,default
set-face global WhitespaceIndent +d@comment

# Assistant
set global ui_options terminal_assistant=cat

# Enable line numbers
hook global WinCreate .* %{
  addhl window/number-lines number-lines
}

# Kitty-specific options
hook -group windowing global KakBegin .* %{
  try %{
    set global kitty_window_type os-window
  }
}

# Comment line and block
map global normal <#> ': comment-line<ret>'
map global normal <a-#> ': comment-block<ret>'

# Go to grep-jump
map global goto f -docstring "current grep-jump match" '<esc>: grep-jump<ret>'

# System clipboard interactions
hook global RegisterModified '"' %{ nop %sh{
  printf "%s" "$kak_main_reg_dquote" | pbcopy >/dev/null 2>/dev/null &
}}
map global user P -docstring "Paste before cursor from clipboard" '! pbpaste -n | cat<ret>'
map global user p -docstring "Paste after cursor from clipboard" '<a-!> pbpaste -n | cat<ret>'
map global user R -docstring "Replace selection with text from clipboard" '<a-d>! pbpaste -n | cat<ret>'
define-command -params 0 -docstring "Copy line down" copyline %{
    execute-keys -draft 'xy'%val{count}'P'
}
map global normal <+> -docstring "Copy line down" ': copyline<ret>'
define-command -params 0 -docstring "Delete current pair of brackets" delete-current-brackets %{
    execute-keys 'm<a-:>'
    execute-keys -draft '<a-S>d'
    execute-keys 'H'
}
map global normal D ": delete-current-brackets<ret>"

# Disable write-to
# unalias global w
# define-command -params 0 -docstring "Writes the current file" w "write"

# Tab sizes
hook global InsertChar \t %{ exec -draft -itersel h@ }
set global tabstop 2
set global indentwidth 2

# Language-specific tabstop with override
hook global WinSetOption filetype=(rust|python) %{
  set window tabstop 4
  set window indentwidth 4
}

# Ctrl + a in insert mode = esc
map global insert <c-a> '<esc>'

# Tab completion
hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

# <a-a> in Insert mode moves to end of line.
map global insert <a-a> '<esc>A'

hook global WinSetOption filetype=(rust) %{
    set-option buffer makecmd "cargo check"
}

def -hidden insert-c-n %{
 try %{
   lsp-snippets-select-next-placeholders
   exec '<a-;>d'
 } catch %{
   exec -with-hooks '<c-n>'
 }
}
map global insert <c-n> "<a-;>: insert-c-n<ret>"

# Use C++ for .h headers
hook global BufCreate .*[.](h) %{
  set-option buffer filetype cpp
}

hook global BufCreate .*[.]kakrc %{
  set-option buffer filetype kak
}

hook global BufCreate .*[.]md %{
  add-highlighter buffer/ wrap
}

hook global BufOpenFile .* %{
  modeline-parse
}

map global normal <a-]> ':inc-dec-modify-numbers + %val{count}<ret>'
map global normal <a-[> ':inc-dec-modify-numbers - %val{count}<ret>'


declare-user-mode ui
map -docstring "UI" global user u ": enter-user-mode ui<ret>"
map -docstring "Disable format on save" global ui f ":remove-hooks window lsp-formatting <ret>"

