#!/usr/bin/env lua

-- Load the sketchybar-package and prepare the helper binaries
-- package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"
require("init")
